#!/data/data/com.termux/files/usr/bin/bash

source core/config.sh
source core/boot.sh
source core/menu.sh

source modules/system.sh
source modules/network.sh
source modules/dns.sh
source modules/hash.sh
source modules/process.sh

boot

while true
do
menu
done
